/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BLL.Products;
import BLL.Inputs;
import BLL.InputDetails;
import BLL.Users;
import DAL.InputDetailsInterface;
import DAL.InputDetailsRespiratory;
import DAL.InputsInterface;
import DAL.InputsRespiratory;
import DAL.ProductsInterface;
import DAL.ProductsRepository;
import DAL.RequestDetailsInterface;
import DAL.RequestDetailsRepository;
import DAL.RequestInterface;
import DAL.RequestRepository;
import DAL.SCHMException;
import gui.model.InputDetailsTableModel;
import gui.model.RequestDetailsTableModel;
import gui.model.RequestTableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EN
 */
public class InputDetailsView extends javax.swing.JInternalFrame {

    /**
     * Creates new form RequestDetails
     */
    public InputDetailsView() {
        initComponents();
        loadTable();
    }
    public int id;
    private static Users users;
    
    public InputDetailsView(int id,Users u) throws SCHMException {
        initComponents();
        this.id = id;
        users = u;
        loadTable();
        r = rir.findById(id);
    }
    InputDetailsInterface cir = new InputDetailsRespiratory();
    InputDetailsTableModel ctm = new InputDetailsTableModel();
    ProductsInterface eir = new ProductsRepository();
    InputsInterface rir = new InputsRespiratory();
    List<InputDetails> list = new ArrayList<>();
    public void loadTable() {
        try {
            list = cir.findByInputID(id);
            ctm.add(list);
            tabela.setModel(ctm);
            ctm.fireTableDataChanged();
        } catch (SCHMException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
//    public boolean kaSasi() throws SCHMException{
//        
//        for (int i = 0; i < list.size(); i++) {
//            Integer pID = list.get(i).getProductID().getBarcode();
//            Products p = eir.findByPOId(pID, 1);
//            if(list.get(i).getQuantity() > p.getQuantity()){
//                return false;
//            }
//        }
//        return true;
//    }
//    public void zbritSasin() throws SCHMException{
//        for (int i = 0; i < list.size(); i++) {
//            Integer pID = list.get(i).getProductID().getBarcode();
//            Products p = eir.findByPOId(pID, 1);
//            p.setQuantity(p.getQuantity()-list.get(i).getQuantity());
//            try {
//                eir.edit(p);
//            } catch (SCHMException es) {
//                JOptionPane.showMessageDialog(this, es.getMessage());
//                return;
//            }
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Inputs r;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
