/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BLL.OrderDetails;
import BLL.Orders;
import DAL.OrderDetailsInterface;
import DAL.OrderDetailsRespiratory;
import DAL.OrdersInterface;
import DAL.OrdersRespiratory;
import DAL.ProductsInterface;
import DAL.ProductsRepository;
import DAL.SCHMException;
import gui.model.OrderDetailsTableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author cc.ks
 */
public class OrderDetailsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderDetailsForm
     */
    OrderDetailsInterface oir = new OrderDetailsRespiratory();
    OrderDetailsTableModel otm = new OrderDetailsTableModel();
    ProductsInterface eir = new ProductsRepository();
    OrdersInterface rir = new OrdersRespiratory();
    List<OrderDetails> list = new ArrayList<>();
    
    public OrderDetailsForm() {
        initComponents();
        loadTable();
    }
    
    private int id;
    
    public OrderDetailsForm(int id) throws SCHMException {
        initComponents();
        this.id = id;
        loadTable();
      
    }
    
      public void loadTable() {
        try {
            list = oir.findByOrderID(id);
            otm.add(list);
            odTable.setModel(otm);
            otm.fireTableDataChanged();
        } catch (SCHMException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        odTable = new javax.swing.JTable();

        setClosable(true);

        odTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(odTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable odTable;
    // End of variables declaration//GEN-END:variables
}
